### ISSUE TITLE
Trim the fat on publishX workflow actions

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#405]
# Description
In order to build+publish packages to github package registry i dont think the specific languages are required

## Action Items
  - [ ] Experiment with `Publish_Backend_Package.yml` and `Publish_Frontend_Package.yml`
    - To run tests with your branch, see below
    - See what happens when you remove the language setup

### Running gh action tests 
Modify this section in the action.yml file
```
on:
  push:
    branches:
      - master
```
to include your branch
```
on:
  push:
    branches:
      - master
      - {{put your branch name here}}
```
